### ISSUE TITLE
M1 Silicon

### ISSUE THREAD

**Issue by pmcnano** [ankane/or-tools-ruby#26]
Having issues getting the gem working on m1 silicon. Tried creating a new rails app, and just adding the gem just to make sure I don't have a conflict with something else but I am receiving the same error.

```/Users/nano/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': dlopen(/Users/nano/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/or-tools-0.6.0/lib/or_tools/ext.bundle, 0x0009): symbol not found in flat namespace '__ZN19operations_research10LinearExprC1EPKNS_10MPVariableE' - /Users/nano/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/or-tools-0.6.0/lib/or_tools/ext.bundle (LoadError)```

Do you have any idea how can I fix this?

**Comment by ankane** [comment]
Hey @pmcnano, check out #25.

**Comment by pmcnano** [comment]
That did the trick, maybe adding to the readme would be nice. Thanks!

**Comment by ankane** [comment]
Added in the commit above.

**Comment by pmcnano** [comment]
Awesome! Thanks again!
