### ISSUE TITLE
[VRP] Add API support for RegisterTransitMatrix?

### ISSUE THREAD

**Issue by spinosa** [ankane/or-tools-ruby#33]
Passing the transit matrix to the C code with [`RegisterTransitMatrix`](https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/ortools/constraint_solver/routing.h#L402-L403) has a significant performance improvement (over a transit callback) in my testing (using the python wrapper).

Would it be possible to support this API?

Thanks, and thanks for your great work with this wrapper!

**Comment by ankane** [comment]
Hey @spinosa, thanks for the suggestion! Added in the commit above.

**Comment by spinosa** [comment]
And it works! Of course. 

Thanks @ankane !

PS Started wandering about your site and repos; awesome stuff.
