### ISSUE TITLE
Add Hint doesn't support Boolean vars.

### ISSUE THREAD

**Issue by joegaudet** [ankane/or-tools-ruby#37]
I have a simple model, with boolean vars for assignment, but it appears that the hint interface only accepts int vars.

Minitest::UnexpectedError: TypeError: Wrong argument type. Expected: ORTools::SatIntVar. Received: ORTools::BoolVar.

**Comment by ankane** [comment]
Hey @joegaudet, thanks for reporting! Added support in the commit above.

**Comment by ankane** [comment]
Great, sounds good!
