### ISSUE TITLE
Problem to install on mac m1

### ISSUE THREAD

**Issue by artur79** [ankane/or-tools-ruby#40]
I struggle with install it on mac m1, getting error related to one of dependencies, looks like architecture does not match

```
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [gobject_introspection.bundle] Error 1

make failed, exit code 2
```

**Comment by artur79** [comment]
seems that updating to 0.8.2 solved that issue, I can see that version does not use all those problematic gems

**Comment by ankane** [comment]
Hey @artur79, I'm not sure how to reproduce, but glad it's working.
