### ISSUE TITLE
Using manylinux version for Apple Silicon

### ISSUE THREAD

**Issue by trumbitta** [ankane/or-tools-ruby#54]
Hey, about https://github.com/ankane/or-tools-ruby/issues/25#issuecomment-982355041 (i.e. adding a package once it's available)

I'm having issues getting the gem to install in docker (Debian Bullseye) on a MacBook M1 Max.

Someone from the ortools repo [suggested](https://github.com/google/or-tools/issues/4007#issuecomment-1833565538) using the [manylinux package](https://github.com/google/or-tools/releases/download/v9.8/ortools-9.8.3296-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl)

Edit: what I mean is for you to make the gem to automatically use the manylinux package on arm64

Wdyt? Good idea? Did I misunderstand their answer?

**Comment by ankane** [comment]
Hi @trumbitta, OR-Tools doesn't provide a [binary distribution](https://developers.google.com/optimization/install/cpp/binary_linux) of the C++ library for ARM for Debian Bullseye, so you'll need to build the OR-Tools C++ library from source and set:

```sh
bundle config build.or-tools --with-or-tools-dir=/path/to/or-tools
```

Then uninstall and reinstall the gem.

**Comment by trumbitta** [comment]
@ankane things are in motion 🤞 https://github.com/google/or-tools/issues/4007#issuecomment-1836093254

**Comment by ankane** [comment]
Great, just pushed a new release with it.

**Comment by trumbitta** [comment]
Works like a charm 👍
