### ISSUE TITLE
Question: is there an equivalent to the Python CpModel.ExportToFile API in this library?

### ISSUE THREAD

**Issue by rpate-ezcater** [ankane/or-tools-ruby#57]
The Python library has an [CpModel.ExportToFile](https://or-tools.github.io/docs/pdoc/ortools/sat/python/cp_model.html#CpModel.ExportToFile) API that can dump a model as a text or binary file.  Is there any equivalent here?

**Comment by ankane** [comment]
Hi @rpate-ezcater, added in the commit above.
