### ISSUE TITLE
adding support for SatParameters.random_seed?

### ISSUE THREAD

**Issue by btc** [ankane/or-tools-ruby#58]
Thank you for this delightful library. It has been a joy to use the CP model and solver.

I am trying to set `random_seed` as `solver.parameters.random_seed`, but `parameters.methods` indicates that `random_seed=` is not present.

Am I missing something? Or perhaps would it be possible to add it?

For reference, [here is the field](https://github.com/google/or-tools/blob/5f7eabb3ffa1de786c224a722f0e9561101c3ab2/ortools/sat/sat_parameters.proto#L343) on the SatParameters protocol definition.

**Comment by ankane** [comment]
Hi @btc, added in the commit above.
